### PR TITLE
steps for PA1/changes for PA1 (Chris Oakden)

### PR DESCRIPTION
**Pull request by coakden**

### CODE REVIEW

**Comment by jvcasillas** [comment]
Hi @coakden, 
Can you delete the ```.DS_Store``` files and resubmit the request? This is some weird system file that only Macs have and it is causing weird merging conflicts.

**Comment by coakden** [comment]
all the .DS_Store files have been deleted

**Comment by jvcasillas** [comment]
All good now. I will merge your commits at the end of the week. Thanks.

**Comment by coakden** [comment]
Thank you!

**Pull request merged**
